name: Update Wiki

on:
  schedule:
    - cron: '0 8-16 * * *'  # Runs every hour from 8 AM to 4 PM
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "WIKI_REPOSITORY_URL=https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" >> $GITHUB_ENV
          echo "CODE_REPOSITORY_URL=https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "BRANCH=main" >> $GITHUB_ENV  # Set the branch variable

      - name: Check for changes in the wiki repository
        id: check_changes
        run: |
          LAST_COMMIT_FILE=".last_commit"
          
          # Fetch the latest commit hash from the wiki repo
          LATEST_COMMIT=$(curl -s "https://api.github.com/repos/${{ github.repository }}.wiki/commits/main" | jq -r '.sha')
          
          # Check if the last commit file exists
          if [ -f $LAST_COMMIT_FILE ]; then
            LAST_COMMIT=$(cat $LAST_COMMIT_FILE)
          else
            LAST_COMMIT=""
          fi

          # Compare the latest commit with the last recorded commit
          if [ "$LATEST_COMMIT" != "$LAST_COMMIT" ]; then
            echo "Changes detected in the wiki repository."
            echo "$LATEST_COMMIT" > $LAST_COMMIT_FILE
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_ENV
          fi

  update-wiki:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: ${{ env.changes == 'true' }}  # Only run if changes were detected
    steps:
      - name: Clone wiki
        run: |
          git clone $WIKI_REPOSITORY_URL wiki
          echo "Cloned wiki repository to 'wiki' directory."

      - name: Verify wiki content
        run: |
          echo "Listing contents of the wiki directory:"
          ls -la wiki
          if [ -z "$(ls -A wiki)" ]; then
            echo "Wiki directory is empty. Cloning may have failed."
            exit 1
          else
            echo "Wiki directory contains files."
          fi

      - name: Copy wiki content to subfolder
        run: |
          mkdir -p wikiSync
          echo "Copying files from wiki to wikiSync directory..."
          cp -r wiki/* wikiSync/
          echo "Contents of wikiSync:"
          ls -la wikiSync/

      - name: Commit and push changes to main repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wikiSync
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update wiki content"
            echo "Changes committed. Pushing to branch $BRANCH."
            git push -f $CODE_REPOSITORY_URL HEAD:$BRANCH  # Push to the main repository's main branch
          else
            echo "No changes to commit."
            echo "Creating an empty commit to trigger actions."
            git commit --allow-empty -m "Triggering action with empty commit"
          fi
