name: Update Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "WIKI_REPOSITORY_URL=https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" >> $GITHUB_ENV
          echo "CODE_REPOSITORY_URL=https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "BRANCH=main" >> $GITHUB_ENV  # Set the branch variable

      - name: Clone wiki into wikiSync
        run: |
          git clone $WIKI_REPOSITORY_URL wikiSync
          echo "Cloned wiki repository into 'wikiSync' directory."

      - name: Verify wiki content
        run: |
          echo "Listing contents of the wikiSync directory:"
          ls -la wikiSync
          if [ -z "$(ls -A wikiSync)" ]; then
            echo "wikiSync directory is empty. Cloning may have failed."
            exit 1
          else
            echo "wikiSync directory contains files."
          fi

      - name: Commit and push changes to main repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wikiSync  # Add the wikiSync directory directly
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update wiki content"
            echo "Changes committed. Pushing to branch $BRANCH."
            git push -f $CODE_REPOSITORY_URL HEAD:$BRANCH  # Push to the main repository's main branch
          else
            echo "No changes to commit. The branch is up to date."
            echo "Exiting workflow."
            exit 0  # End the workflow gracefully
          fi
