name: Update Wiki

on:
  schedule:
    - cron: '0 8-16 * * *'  # Runs every hour from 8 AM to 4 PM
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "WIKI_REPOSITORY_URL=https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" >> $GITHUB_ENV
          echo "CODE_REPOSITORY_URL=https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "BRANCH=main" >> $GITHUB_ENV  # Set the branch variable

      - name: Clone wiki
        run: |
          git clone $WIKI_REPOSITORY_URL wiki
          echo "Cloned wiki repository to 'wiki' directory."

      - name: Check for updates in wiki
        run: |
          git fetch origin main  # Fetch the latest changes
          if [ "$(git rev-list HEAD...origin/main --count)" -gt 0 ]; then
            echo "Updates found in the wiki."
          else
            echo "No updates found in the wiki. Exiting."
            exit 0  # Exit if no updates
          fi

      - name: Verify wiki content
        run: |
          echo "Listing contents of the wiki directory:"
          ls -la wiki
          if [ -z "$(ls -A wiki)" ]; then
            echo "Wiki directory is empty. Cloning may have failed."
            exit 1
          else
            echo "Wiki directory contains files."
          fi

      - name: Copy wiki content to subfolder
        run: |
          mkdir -p wikiSync
          echo "Copying files from wiki to wikiSync directory..."
          cp -r wiki/* wikiSync/
          echo "Contents of wikiSync:"
          ls -la wikiSync/

      - name: Commit and push changes to main repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wikiSync  # Only add the wikiSync directory
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update wikiSync content"
            echo "Changes committed. Pushing to branch $BRANCH."
            git push -f $CODE_REPOSITORY_URL HEAD:$BRANCH
          else
            echo "No changes to commit."
            echo "Creating an empty commit to trigger actions."
            git commit --allow-empty -m "Triggering action with empty commit"
          fi
